version: "3"

services:
  app:
    container_name: cprod
    image: naldfranc/cprod:1.0
    build: 
      context: cprod
      dockerfile: Dockerfile
    volumes:
      - /cprod:/cprod
    ports:
      - 8000:8000
      - 5441:5441
    working_dir: /cprod